"""add loans table

Revision ID: 95cf2099a389
Revises: e4471ff2267c
Create Date: 2025-12-18 16:42:55.032460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95cf2099a389"
down_revision: Union[str, Sequence[str], None] = "e4471ff2267c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("copy_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "RETURNED", name="loan_status"), nullable=False),
        sa.Column("loaned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loans_user_id"), "loans", ["user_id"], unique=False)
    op.create_index(op.f("ix_loans_copy_id"), "loans", ["copy_id"], unique=False)
    op.create_index(op.f("ix_loans_id"), "loans", ["id"], unique=False)
    # tylko jeden ACTIVE loan na copy_id (Postgres partial unique index)
    op.create_index(
        "uq_loans_active_copy_id",
        "loans",
        ["copy_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_loans_active_copy_id", table_name="loans")
    op.drop_index(op.f("ix_loans_user_id"), table_name="loans")
    op.drop_index(op.f("ix_loans_id"), table_name="loans")
    op.drop_index(op.f("ix_loans_copy_id"), table_name="loans")
    op.drop_table("loans")
    # ### end Alembic commands ###
