classDiagram

class User {
    +int id
    +string email
    +string hashed_password
    +string full_name
    +bool is_active
    +datetime created_at
    +datetime updated_at
    +UserRole role
}

class UserRole {
    <<enumeration>>
    READER
    LIBRARIAN
    ADMIN
}

class Author {
    +int id
    +string full_name
    +datetime created_at
    +datetime updated_at
}

class Book {
    +int id
    +string title
    +string isbn
    +int published_year
    +datetime created_at
    +datetime updated_at
}

class Copy {
    +int id
    +string inventory_code
    +CopyStatus status
    +datetime created_at
    +datetime updated_at
}

class CopyStatus {
    <<enumeration>>
    AVAILABLE
    BORROWED
    LOST
    DAMAGED
}

User --> UserRole : role

Author "1" --> "many" Book : writes
Book "1" --> "many" Copy : contains

Copy --> CopyStatus : status
